/**
 * @module DebitNoteCodes - Catálogo No. 09 (Códigos de tipo de nota de crédito electrónica)
 */

module.exports = {
  ANULACION_OPERACION: '01',
  ANULACION_ERROR_RUC: '02',
  CORRECCION_ERROR_DESCRIPCION: '03',
  DESCUENTO_GLOBAL: '04',
  DESCUENTO_ITEM: '05',
  DEVOLUCION_TOTAL: '06',
  DEVOLUCION_ITEM: '07',
  BONIFICACION: '08',
  DISMINUCION_VALOR: '09',
  OTROS_CONCEPTOS: '10',
  AJUSTES_OPERACIONES_EXPORTACION: '11',
  AJUSTES_AFECTOS_IVAP: '12'
}
