/**
 * @module DocumentLegend - Catálogo No. 52 (Códigos de leyendas - Descripción)
 */

module.exports = {
  TRANSFERENCIA_GRATUITA: 'TRANSFERENCIA GRATUITA DE UN BIEN Y/O SERVICIO PRESTADO GRATUITAMENTE',
  COMPROBANTE_PERCEPCION: 'COMPROBANTE DE PERCEPCIÓN',
  BIENES_TRANSFERIDOS_AMAZONIA: 'BIENES TRANSFERIDOS EN LA AMAZONÍA REGIÓN SELVA PARA SER CONSUMIDOS EN LA MISMA',
  SERVICIOS_PRESTADOS_AMAZONIA: 'SERVICIOS PRESTADOS EN LA AMAZONÍA  REGIÓN SELVA PARA SER CONSUMIDOS EN LA MISMA',
  CONTRATOS_CONSTRUCCION_AMAZONIA: 'CONTRATOS DE CONSTRUCCIÓN EJECUTADOS  EN LA AMAZONÍA REGIÓN SELVA',
  AGENCIA_VIAJE_PAQUETE_TURISTICO: 'Agencia de Viaje - Paquete turístico',
  VENTA_REALIZADA_EMISOR_ITINERANTE: 'Venta realizada por emisor itinerante',
  OPERACION_SUJETA_DETRACCION: 'Operación sujeta a detracción',
  OPERACION_SUJETA_IVAP: 'Operación sujeta al IVAP',
  VENTA_EXONERADA_IGV_ISC_IPM: 'VENTA EXONERADA DEL IGV-ISC-IPM. PROHIBIDA LA VENTA FUERA DE LA ZONA COMERCIAL DE TACNA',
  PRIMERA_VENTA_USUARIOS_ZONA_COMERCIAL: 'PRIMERA VENTA DE MERCANCÍA IDENTIFICABLE ENTRE USUARIOS DE LA ZONA COMERCIAL'
}
