/**
 * @module DocumentLegendCodes - Catálogo No. 52 (Códigos de leyendas - Código)
 */

module.exports = {
  MONTO_LETRAS: '1000',
  TRANSFERENCIA_GRATUITA: '1002',
  COMPROBANTE_PERCEPCION: '2000',
  BIENES_TRANSFERIDOS_AMAZONIA: '2001',
  SERVICIOS_PRESTADOS_AMAZONIA: '2002',
  CONTRATOS_CONSTRUCCION_AMAZONIA: '2003',
  AGENCIA_VIAJE_PAQUETE_TURISTICO: '2004',
  VENTA_REALIZADA_EMISOR_ITINERANTE: '2005',
  OPERACION_SUJETA_DETRACCION: '2006',
  OPERACION_SUJETA_IVAP: '2007',
  VENTA_EXONERADA_IGV_ISC_IPM: '2008',
  PRIMERA_VENTA_USUARIOS_ZONA_COMERCIAL: '2009',
  RESTITUCION_SIMPLIFICADO_DERECHOS_ARANCELARIOS: '2010'
}
