/**
 * @module OperationTypeCodes - Catálogo No. 51 (Código de tipo de operación)
 */

module.exports = {
  VENTA_INTERNA: '0101',
  VENTA_INTERNA_SUSTENTA_GASTOS_DEDUCIBLES_PERSONA_NATURAL: '0112',
  VENTA_INTERNA_NRUS: '0113',
  EXPORTACION_BIENES: '0200',
  EXPORTACION_SERVICIOS_REALIZADOS_INTEGRAMENTE_PAIS: '0201',
  EXPORTACION_SERVICIOS_HOSPEDAJE_NO_DOMICILIADO: '0202',
  EXPORTACION_SERVICIOS_TRANSPORTE_NAVIERAS: '0203',
  EXPORTACION_SERVICIOS_NAVES_AERONAVES_BANDERA_EXTRANJERA: '0204',
  EXPORTACION_SERVICIOS_CONFORMEN_PAQUETE_TURISTICO: '0205',
  EXPORTACION_SERVICIOS_COMPLEMENTARIOS_TRANSPORTE_CARGA: '0206',
  EXPORTACION_SERVICIOS_SEA_DOMICILIADOS_ZED: '0207',
  EXPORTACION_SERVICIOS_REALIZADOS_PARCIALMENTE_EXTRANJERO: '0208',
  OPERACIONES_CARTA_PORTE_AEREO: '0301',
  OPERACIONES_TRANSPORTE_FERROVIARIO_PASAJEROS: '0302',
  OPERACIONES_PAGO_REGALIA_PETROLERA: '0303',
  VENTAS_NO_DOMICILIADOS_NO_EXPORTACION: '0401',
  OPERACION_DETRACCION: '1001',
  OPERACION_DETRACCION_RECURSOS_HIDROBIOLOGICOS: '1002',
  OPERACION_DETRACCION_SERVICIOS_TRANSPORTE_PASAJEROS: '1003',
  OPERACION_DETRACCION_SERVICIOS_TRANSPORTE_CARGA: '1004',
  OPERACION_PERCEPCION: '2001'
}
