/**
 * @module TaxExemptionReasonCodes - Catálogo No. 07 (Código de tipo de afectación del IGV)
 */

module.exports = {
  GRAVADA_OPERACION_ONEROSA: '10',
  GRAVADA_RETIRO_PREMIO: '11',
  GRAVADA_RETIRO_DONACION: '12',
  GRAVADA_RETIRO: '13',
  GRAVADA_RETIRO_PUBLICIDAD: '14',
  GRAVADA_BONIFICACION: '15',
  GRAVADA_RETIRO_ENTREGA_TRABAJADORES: '16',
  GRAVADA_IVAP: '17',
  EXONERADA_OPERACION_ONEROSA: '20',
  EXONERADA_TRANSFERENCIA_GRATUITA: '21',
  INAFECTO_OPERACION_ONEROSA: '30',
  INAFECTO_RETIRO_BONIFICACION: '31',
  INAFECTO_RETIRO: '32',
  INAFECTO_RETIRO_MUESTRAS_MEDICAS: '33',
  INAFECTO_RETIRO_CONVENIO_COLECTIVO: '34',
  INAFECTO_RETIRO_PREMIO: '35',
  INAFECTO_RETIRO_PUBLICIDAD: '36',
  INAFECTO_TRANSFERENCIA_GRATUITA: '37',
  EXPORTACION_BIENES_SERVICIOS: '40'
}
