"use strict";

exports.Pais = require('./CodigosPais');
exports.Ubigeos = require('./CodigosUbigeo');
exports.Leyenda = require('./CodigosLeyendas');
exports.EstadoItem = require('./CodigosEstadoItem');
exports.TipoMoneda = require('./CodigosTipoMoneda');
exports.TipoTributo = require('./CodigosTipoTributo');
exports.TipoDocumento = require('./CodigosTipoDocumento');
exports.TipoOperacion = require('./CodigosTipoOperacion');
exports.TipoValorVenta = require('./CodigosTipoValorVenta');
exports.TipoNotaDebito = require('./CodigosTipoNotaDebito');
exports.TipoNotaCredito = require('./CodigosTipoNotaCredito');
exports.CargoDescuento = require('./CodigosCargosDescuentos');
exports.RegimenRetencion = require('./CodigosRegimenRetencion');
exports.TipoAfectacionIgv = require('./CodigosTipoAfectacionIgv');
exports.RegimenPercepcion = require('./CodigosRegimenPercepcion');
exports.TipoSistemaIsc = require('./CodigosTipoSistemaCalculoIsc');
exports.TipoPrecioVenta = require('./CodigosTipoPrecioVentaUnitario');
exports.TipoDocumentoIdentidad = require('./CodigosTipoDocumentoIdentidad');
exports.DocumentoRelacionado = require('./CodigosDocumentosRelacionadosTributarios');
